/**
 * @file tpl_external_interrupts.c
 *
 * @section desc File description
 *
 * External interrupts init and acknowledge functions for lab1
 * Automatically generated by goil on Fri Dec  8 10:16:07 2017
 * from root OIL file lab1.oil
 *
 * @section copyright Copyright
 *
 * Trampoline OS
 *
 * Trampoline is copyright (c) IRCCyN 2005-2007
 * Trampoline is protected by the French intellectual property law.
 *
 * This software is distributed under the Lesser GNU Public Licence
 *
 * @section infos File informations
 *
 * $Date$
 * $Rev$
 * $Author$
 * $URL$
 */

#include "tpl_machine.h"


/*
 * External Interrupts initialization for the mk20dx256/teensy31 Microcontroller
 *
 * Interrupt vectors are PORTA_IRQ, PORTB_IRQ, PORTC_IRQ, PORTD_IRQ and
 * PORTE_IRQ,
 *
 * Inits are done according to the source(s) pin(s) selected for an interrupt
 * vector corresponding to an or a set of interrupt(s) line(s)
 */
#define OS_START_SEC_CODE
#include "tpl_memmap.h"

FUNC(void, OS_CODE) tpl_init_external_interrupts()
{
}

#define OS_STOP_SEC_CODE
#include "tpl_memmap.h"

/* End of file tpl_external_interrupts.c */

